Feature/07 basefragment
Team-Finder-dev/TeamFinder_android pull request #11
Opened 2024-03-19 11:33 UTC by GoetzDeBouville

Добавляет базовые фрагмент и активити
Реализует наследование MainActivity от  базовой активити
Добавляет класс Application

2024-03-19 18:50 UTC, n-shvedov27 requested changes

2024-03-19 18:50 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseActivity.kt
>  abstract class BaseActivity<VB : ViewBinding>(
Подскажи, зачем нам BaseActivity?
У нас же singleActivity подход)

2024-03-19 18:50 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseFragment.kt
> +    abstract fun subscribe()
Давай будем добавлять методы (initViews и subscribe) по мере надобности, чтобы они потом не потерялись

2024-03-20 12:04 UTC, GoetzDeBouville commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseActivity.kt
>  abstract class BaseActivity<VB : ViewBinding>(
на случай если будет доп активити, плюс разгрузить код в реализации активити. Но ок, удалю

2024-03-20 12:09 UTC, GoetzDeBouville commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseFragment.kt
> +    abstract fun subscribe()
Пофиксил

2024-03-20 13:55 UTC, n-shvedov27 approved these changes

2024-03-20 13:55 UTC, merged