01 base set
Team-Finder-dev/TeamFinder_android pull request #12
Opened 2024-03-19 13:03 UTC by GoetzDeBouville

2024-03-19 18:22 UTC, n-shvedov27 requested changes

2024-03-19 18:22 UTC, n-shvedov27 commented on gradle/libs.versions.toml
> +lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
Кажется эта зависимость нигде не используется

2024-03-19 18:22 UTC, n-shvedov27 commented on gradle/libs.versions.toml
>  agp = "8.3.0"
Давай плз agp 8.2 поставим
У кого студия ниже игуаны проект собрать не смогут иначе

2024-03-19 18:35 UTC, n-shvedov27 requested changes
Я мб ошибаюсь, но как будто в .gitignore надо еще папку .idea целиком добавить
<img width="332" alt="Снимок экрана 2024-03-19 в 23 34 19" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/d30c556e-e13c-4bc3-b77d-1ac52b4b98ce">
Почему-то файлы все еще попадают в индекс гита

2024-03-19 18:38 UTC, GoetzDeBouville commented on gradle/libs.versions.toml
> +lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
Не используются, я добавил заранее

2024-03-19 18:47 UTC, GoetzDeBouville commented on gradle/libs.versions.toml
>  agp = "8.3.0"
Установил 8.2.0

2024-03-19 18:48 UTC, GoetzDeBouville commented on gradle/libs.versions.toml
> +lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
Удалил из build.gradle, но в toml оставил, подключим на тасках, когда это потребуется

2024-03-19 18:58 UTC, n-shvedov27 commented on gradle/libs.versions.toml
> +lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
Старайся плз добавлять только то что  реально нужно в рамках текущего ПРа
"Код на будущее" часто забывается и теряется

2024-03-19 18:59 UTC, n-shvedov27 requested changes
Поправь еще [это](https://github.com/Team-Finder-dev/TeamFinder_android/pull/12#pullrequestreview-1947076653) плз и сольем)

2024-03-20 11:20 UTC, n-shvedov27 approved these changes

2024-03-20 11:20 UTC, merged