03 Прописаны шрифты и стили
Team-Finder-dev/TeamFinder_android pull request #14
Opened 2024-03-20 19:01 UTC by NikolayRyabcev

2024-03-21 12:42 UTC, n-shvedov27 requested changes

2024-03-21 12:42 UTC, n-shvedov27 commented on .idea/vcs.xml
Подтяни плз в ветку актуальный дев
Папки .idea в ПРе не должно быть)

2024-03-21 12:42 UTC, n-shvedov27 commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">64sp</item>
<item name="android:textSize">57sp</item>

Размер из поля size берем)
<img width="239" alt="Снимок экрана 2024-03-21 в 17 40 04" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/7e4bf862-e682-4c5d-9516-d595307d7f4b">

2024-03-22 04:59 UTC, NikolayRyabcev commented on .idea/vcs.xml
готово

2024-03-22 04:59 UTC, NikolayRyabcev commented on app/src/main/res/values/styles.xml
> +        <item name="android:textSize">64sp</item>
готово

2024-03-22 05:04 UTC, n-shvedov27 commented on .idea/vcs.xml
В диффе все еще есть папка .idea)
<img width="498" alt="Снимок экрана 2024-03-22 в 10 03 37" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/23e3f24b-d70a-4db7-9a98-66fbf70d7fd7">

2024-03-25 17:08 UTC, n-shvedov27 approved these changes

2024-03-25 17:10 UTC, n-shvedov27 requested changes

2024-03-25 17:10 UTC, n-shvedov27 commented on .gitignore
> +.gradle
А зачем тебе тут изменения?)

2024-03-25 17:12 UTC, n-shvedov27 approved these changes

2024-03-25 17:14 UTC, merged