Feature/10 baseviewmodel
Team-Finder-dev/TeamFinder_android pull request #16
Opened 2024-03-21 11:18 UTC by GoetzDeBouville

Добавляет базовую вью модель с реализацией интерфейса NavEvent

2024-03-21 15:32 UTC, n-shvedov27 requested changes

2024-03-21 15:32 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseFragment.kt
> +        lifecycleScope.launch {
а почему бы сразу в onCreateView и не подписаться?

2024-03-21 16:14 UTC, GoetzDeBouville commented on app/src/main/java/com/teamfinder/teamfinder/base/BaseFragment.kt
> +        lifecycleScope.launch {
Вынес подписку в onCreateView

2024-03-22 04:21 UTC, n-shvedov27 approved these changes

2024-03-22 04:21 UTC, merged