detekt
Team-Finder-dev/TeamFinder_android pull request #23
Opened 2024-03-21 22:26 UTC by DimaK21

detekt и action github для него

2024-03-21 22:33 UTC, DimaK21 commented
Собака-комментатор не работает. Либо я что-то не дописал, либо в настройках репозитория нужно что-то сделать.

2024-03-22 04:40 UTC, n-shvedov27 requested changes

2024-03-22 04:40 UTC, n-shvedov27 commented on .github/workflows/assemble.yml
> +
А разве не достаточно просто перед `- name: Assemble app` добавить `./gradlew detekt` ?)

2024-03-22 04:40 UTC, n-shvedov27 commented on settings.gradle.kts
> +includeBuild("build-logic")
Зачем тебе этот модуль?

2024-03-22 05:10 UTC, DimaK21 commented on settings.gradle.kts
> +includeBuild("build-logic")
с него и запускается detek)
но да, смысла нет, вечером уберу их и поставлю запуск с ./gradlew detekt

2024-03-22 18:22 UTC, DimaK21 commented
@n-shvedov27 убрал модули градла, убрал ревью собаку
не понимаю как результаты детекта показать
сделал просто загрузку артефакта отчета и загрузку отчета в формате sarif в github

2024-03-24 13:43 UTC, DimaK21 commented
@n-shvedov27 немного переделал
убрал загрузку sarif в github
теперь если detekt ругается, то проверку не проходит
на всякий случай красивый html с ошибками загружается в артефакты
Но теперь проблема, проверку detekt не проходит код, который уже есть в ветке dev

2024-03-25 04:26 UTC, n-shvedov27 commented
Подтяни себе в ветку dev, поправь замечания и сольем уже

2024-03-25 04:27 UTC, n-shvedov27 requested changes

2024-03-25 04:27 UTC, n-shvedov27 commented on .github/workflows/assemble.yml
> +    branches: [ "main", "dev", "devtest" ]
Заодно devtest убери плз
Кажется она больше не нужна

2024-03-25 17:06 UTC, n-shvedov27 approved these changes

2024-03-25 17:06 UTC, merged