08 dagger
Team-Finder-dev/TeamFinder_android pull request #31
Opened 2024-03-22 15:12 UTC by Megrief

Добавлено: 
- инициализация Dagger в App
- AppComponent
- модуль ViewModelModule
- inject ViewModel'ей во фрагменты

2024-03-25 04:46 UTC, n-shvedov27 requested changes

2024-03-25 04:46 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/di/ViewModelModule.kt
> +    abstract fun contactsViewModel(contactsViewModel: ContactsViewModel): ViewModel
Не хорошо, что у нас все зависимости в одном компоненте, для каждого экрана должен быть свой компонент

2024-03-25 04:46 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/presentation/searchscreen/SearchFragment.kt
> +        viewModel = ViewModelProvider(viewModelStore, factory)[SearchViewModel::class.java]
По хорошему бы вынести эту логику в BaseFragment

По типу этого
<img width="752" alt="Снимок экрана 2024-03-25 в 09 45 30" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/24c58c6b-c21f-49e9-8452-4f0f5bcf9c9e">
<img width="428" alt="Снимок экрана 2024-03-25 в 09 45 43" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/13aaf950-b114-4c3b-8350-be28b38884f6">

<img width="481" alt="Снимок экрана 2024-03-25 в 09 45 59" src="https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/a5bff035-e4f4-4c97-98ac-f25e5443a2b2">

2024-03-25 04:58 UTC, Megrief commented on app/src/main/java/com/teamfinder/teamfinder/di/ViewModelModule.kt
> +    abstract fun contactsViewModel(contactsViewModel: ContactsViewModel): ViewModel
Доброго утра. Хочу уточнить: для каждого экрана свой компонент, но модуль один, или модули тоже отдельные создавать?

2024-03-25 05:06 UTC, Megrief commented on app/src/main/java/com/teamfinder/teamfinder/presentation/searchscreen/SearchFragment.kt
> +        viewModel = ViewModelProvider(viewModelStore, factory)[SearchViewModel::class.java]
Можно, пожалуйста, пример: как это будет выглядеть в финальном фрагменте?

Сейчас у меня такой вариант:

![изображение_2024-03-25_100200368](https://github.com/Team-Finder-dev/TeamFinder_android/assets/109866375/fcb0c878-50d7-4334-8497-4c08f4985874)

2024-03-25 17:07 UTC, n-shvedov27 commented
Нужно подтянуть дев с детектом

2024-03-25 17:08 UTC, n-shvedov27 requested changes
Нужно подтянуть дев с детектом

2024-03-26 04:36 UTC, Megrief commented
@n-shvedov27 готово.

2024-03-26 05:14 UTC, n-shvedov27 approved these changes

2024-03-26 05:14 UTC, merged