26 team details screen
Team-Finder-dev/TeamFinder_android pull request #43
Opened 2024-03-28 05:54 UTC by besmax

2024-03-28 07:32 UTC, n-shvedov27 requested changes
Билд упал

2024-03-29 06:45 UTC, n-shvedov27 requested changes
Добавь плз возможность перейти в приложении на эти экраны
Например кнопку в TeamsSearchFragment

2024-03-29 06:45 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/feature/teamdetails/presentation/basic/TeamDetailsBasicFragment.kt
> +class TeamDetailsBasicFragment :
Для чего нужен TeamDetailsBasicFragment и TeamDetailsInfoFragment?
У тебя же для деталей команды должен быть один экран

2024-03-30 06:17 UTC, besmax commented on app/src/main/java/com/teamfinder/teamfinder/feature/teamdetails/presentation/basic/TeamDetailsBasicFragment.kt
> +class TeamDetailsBasicFragment :
Там таблайоут с 2 фрагментами
![image](https://github.com/Team-Finder-dev/TeamFinder_android/assets/88286767/b639e2f4-2450-44a4-82f2-ae857b8f615b)

2024-04-01 10:14 UTC, n-shvedov27 approved these changes

2024-04-01 10:14 UTC, merged