[#27] Экран деталей игрока
Team-Finder-dev/TeamFinder_android pull request #46
Opened 2024-04-01 16:43 UTC by DimaK21

Добавлен экран деталей игрока (эпик Поиск игрока)

2024-04-03 05:10 UTC, n-shvedov27 requested changes

2024-04-03 05:10 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/feature/playerssearchdetails/di/PlayersSearchDetailsComponent.kt
> +        PlayersSearchDetailsInfoModule::class
Думаю в данном случае все эти 4 модуля можно в один объедениить

2024-04-03 17:09 UTC, DimaK21 commented on app/src/main/java/com/teamfinder/teamfinder/feature/playerssearchdetails/di/PlayersSearchDetailsComponent.kt
> +        PlayersSearchDetailsInfoModule::class
@n-shvedov27 объединил в 1 модуль

2024-04-04 06:07 UTC, n-shvedov27 approved these changes

2024-04-04 06:08 UTC, n-shvedov27 approved these changes

2024-04-04 06:11 UTC, merged