[#30] Экран логина
Team-Finder-dev/TeamFinder_android pull request #47
Opened 2024-04-01 17:27 UTC by DimaK21

Добавлен экран логина

2024-04-03 05:43 UTC, n-shvedov27 requested changes

2024-04-03 05:43 UTC, n-shvedov27 commented on app/src/main/java/com/teamfinder/teamfinder/feature/registration/presentation/AuthLoginFragment.kt
> +    override fun diComponent(): ScreenComponent = DaggerRegistrationComponent.create()
Это же отдельный экран
Почему компонент не AuthLoginComponent

2024-04-03 17:27 UTC, DimaK21 commented on app/src/main/java/com/teamfinder/teamfinder/feature/registration/presentation/AuthLoginFragment.kt
> +    override fun diComponent(): ScreenComponent = DaggerRegistrationComponent.create()
Сделал отдельный Component

2024-04-04 06:01 UTC, n-shvedov27 approved these changes

2024-04-04 06:01 UTC, merged