17_issue
Team-Finder-dev/TeamFinder_android pull request #48
Opened 2024-04-02 05:25 UTC by Megrief

Сделана верстка экрана Контакты. 
Без AppBar и BottomNavigationView

2024-04-03 05:31 UTC, n-shvedov27 requested changes

2024-04-03 05:31 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_contacts.xml
> +        <androidx.appcompat.widget.AppCompatTextView
А почему не обычные TextView и ImageView?

2024-04-03 05:45 UTC, Megrief commented on app/src/main/res/layout/fragment_contacts.xml
> +        <androidx.appcompat.widget.AppCompatTextView
Преимуществ не знаю.
Решил раз уж в зависимостях везде androidx, то и тут использовать все из более свежей библиотеки.

2024-04-04 06:30 UTC, n-shvedov27 commented on app/src/main/res/layout/fragment_contacts.xml
> +        <androidx.appcompat.widget.AppCompatTextView
![photo_2024-04-04 11 29 22](https://github.com/Team-Finder-dev/TeamFinder_android/assets/37715977/1fe045d1-f5c4-40a8-843c-280b5fff0e05)

 У меня просто не все картинки отображаются
 Видимо нужно или на ImageView заменить или на srcCompat

2024-04-04 06:33 UTC, Megrief commented
@n-shvedov27 Исправил конфликты.

2024-04-04 06:39 UTC, Megrief commented on app/src/main/res/layout/fragment_contacts.xml
> +        <androidx.appcompat.widget.AppCompatTextView
Проверил. Дело не в этом. Поищу проблему.

2024-04-04 06:47 UTC, Megrief commented on app/src/main/res/layout/fragment_contacts.xml
> +        <androidx.appcompat.widget.AppCompatTextView
@n-shvedov27 готово. Некорректно отображались иконки из папки anyDpi

2024-04-05 05:34 UTC, n-shvedov27 approved these changes

2024-04-05 05:35 UTC, merged